// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/flow.proto

package com.changwu.flowCenterProtobuf;

public final class FlowProtos {
  private FlowProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FlowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Flow.Flow)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string flowType = 1;</code>
     * @return The flowType.
     */
    java.lang.String getFlowType();
    /**
     * <code>string flowType = 1;</code>
     * @return The bytes for flowType.
     */
    com.google.protobuf.ByteString
        getFlowTypeBytes();

    /**
     * <code>map&lt;string, string&gt; roleMap = 2;</code>
     */
    int getRoleMapCount();
    /**
     * <code>map&lt;string, string&gt; roleMap = 2;</code>
     */
    boolean containsRoleMap(
        java.lang.String key);
    /**
     * Use {@link #getRoleMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getRoleMap();
    /**
     * <code>map&lt;string, string&gt; roleMap = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getRoleMapMap();
    /**
     * <code>map&lt;string, string&gt; roleMap = 2;</code>
     */

    java.lang.String getRoleMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; roleMap = 2;</code>
     */

    java.lang.String getRoleMapOrThrow(
        java.lang.String key);

    /**
     * <code>string applicate = 3;</code>
     * @return The applicate.
     */
    java.lang.String getApplicate();
    /**
     * <code>string applicate = 3;</code>
     * @return The bytes for applicate.
     */
    com.google.protobuf.ByteString
        getApplicateBytes();

    /**
     * <code>int32 departmentId = 4;</code>
     * @return The departmentId.
     */
    int getDepartmentId();

    /**
     * <code>int32 recordId = 5;</code>
     * @return The recordId.
     */
    int getRecordId();
  }
  /**
   * Protobuf type {@code Flow.Flow}
   */
  public static final class Flow extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Flow.Flow)
      FlowOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Flow.newBuilder() to construct.
    private Flow(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Flow() {
      flowType_ = "";
      applicate_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Flow();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Flow(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              flowType_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                roleMap_ = com.google.protobuf.MapField.newMapField(
                    RoleMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              roleMap__ = input.readMessage(
                  RoleMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              roleMap_.getMutableMap().put(
                  roleMap__.getKey(), roleMap__.getValue());
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              applicate_ = s;
              break;
            }
            case 32: {

              departmentId_ = input.readInt32();
              break;
            }
            case 40: {

              recordId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.changwu.flowCenterProtobuf.FlowProtos.internal_static_Flow_Flow_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetRoleMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.changwu.flowCenterProtobuf.FlowProtos.internal_static_Flow_Flow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.changwu.flowCenterProtobuf.FlowProtos.Flow.class, com.changwu.flowCenterProtobuf.FlowProtos.Flow.Builder.class);
    }

    public static final int FLOWTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object flowType_;
    /**
     * <code>string flowType = 1;</code>
     * @return The flowType.
     */
    @java.lang.Override
    public java.lang.String getFlowType() {
      java.lang.Object ref = flowType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flowType_ = s;
        return s;
      }
    }
    /**
     * <code>string flowType = 1;</code>
     * @return The bytes for flowType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFlowTypeBytes() {
      java.lang.Object ref = flowType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flowType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROLEMAP_FIELD_NUMBER = 2;
    private static final class RoleMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.changwu.flowCenterProtobuf.FlowProtos.internal_static_Flow_Flow_RoleMapEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> roleMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetRoleMap() {
      if (roleMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RoleMapDefaultEntryHolder.defaultEntry);
      }
      return roleMap_;
    }

    public int getRoleMapCount() {
      return internalGetRoleMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; roleMap = 2;</code>
     */

    @java.lang.Override
    public boolean containsRoleMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetRoleMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getRoleMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getRoleMap() {
      return getRoleMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; roleMap = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getRoleMapMap() {
      return internalGetRoleMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; roleMap = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getRoleMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetRoleMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; roleMap = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getRoleMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetRoleMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int APPLICATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object applicate_;
    /**
     * <code>string applicate = 3;</code>
     * @return The applicate.
     */
    @java.lang.Override
    public java.lang.String getApplicate() {
      java.lang.Object ref = applicate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        applicate_ = s;
        return s;
      }
    }
    /**
     * <code>string applicate = 3;</code>
     * @return The bytes for applicate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getApplicateBytes() {
      java.lang.Object ref = applicate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        applicate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPARTMENTID_FIELD_NUMBER = 4;
    private int departmentId_;
    /**
     * <code>int32 departmentId = 4;</code>
     * @return The departmentId.
     */
    @java.lang.Override
    public int getDepartmentId() {
      return departmentId_;
    }

    public static final int RECORDID_FIELD_NUMBER = 5;
    private int recordId_;
    /**
     * <code>int32 recordId = 5;</code>
     * @return The recordId.
     */
    @java.lang.Override
    public int getRecordId() {
      return recordId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFlowTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, flowType_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetRoleMap(),
          RoleMapDefaultEntryHolder.defaultEntry,
          2);
      if (!getApplicateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, applicate_);
      }
      if (departmentId_ != 0) {
        output.writeInt32(4, departmentId_);
      }
      if (recordId_ != 0) {
        output.writeInt32(5, recordId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFlowTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, flowType_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetRoleMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        roleMap__ = RoleMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, roleMap__);
      }
      if (!getApplicateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, applicate_);
      }
      if (departmentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, departmentId_);
      }
      if (recordId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, recordId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.changwu.flowCenterProtobuf.FlowProtos.Flow)) {
        return super.equals(obj);
      }
      com.changwu.flowCenterProtobuf.FlowProtos.Flow other = (com.changwu.flowCenterProtobuf.FlowProtos.Flow) obj;

      if (!getFlowType()
          .equals(other.getFlowType())) return false;
      if (!internalGetRoleMap().equals(
          other.internalGetRoleMap())) return false;
      if (!getApplicate()
          .equals(other.getApplicate())) return false;
      if (getDepartmentId()
          != other.getDepartmentId()) return false;
      if (getRecordId()
          != other.getRecordId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FLOWTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFlowType().hashCode();
      if (!internalGetRoleMap().getMap().isEmpty()) {
        hash = (37 * hash) + ROLEMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetRoleMap().hashCode();
      }
      hash = (37 * hash) + APPLICATE_FIELD_NUMBER;
      hash = (53 * hash) + getApplicate().hashCode();
      hash = (37 * hash) + DEPARTMENTID_FIELD_NUMBER;
      hash = (53 * hash) + getDepartmentId();
      hash = (37 * hash) + RECORDID_FIELD_NUMBER;
      hash = (53 * hash) + getRecordId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.changwu.flowCenterProtobuf.FlowProtos.Flow prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Flow.Flow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Flow.Flow)
        com.changwu.flowCenterProtobuf.FlowProtos.FlowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.changwu.flowCenterProtobuf.FlowProtos.internal_static_Flow_Flow_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetRoleMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableRoleMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.changwu.flowCenterProtobuf.FlowProtos.internal_static_Flow_Flow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.changwu.flowCenterProtobuf.FlowProtos.Flow.class, com.changwu.flowCenterProtobuf.FlowProtos.Flow.Builder.class);
      }

      // Construct using com.changwu.Flow.FlowProtos.Flow.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        flowType_ = "";

        internalGetMutableRoleMap().clear();
        applicate_ = "";

        departmentId_ = 0;

        recordId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.changwu.flowCenterProtobuf.FlowProtos.internal_static_Flow_Flow_descriptor;
      }

      @java.lang.Override
      public com.changwu.flowCenterProtobuf.FlowProtos.Flow getDefaultInstanceForType() {
        return com.changwu.flowCenterProtobuf.FlowProtos.Flow.getDefaultInstance();
      }

      @java.lang.Override
      public com.changwu.flowCenterProtobuf.FlowProtos.Flow build() {
        com.changwu.flowCenterProtobuf.FlowProtos.Flow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.changwu.flowCenterProtobuf.FlowProtos.Flow buildPartial() {
        com.changwu.flowCenterProtobuf.FlowProtos.Flow result = new com.changwu.flowCenterProtobuf.FlowProtos.Flow(this);
        int from_bitField0_ = bitField0_;
        result.flowType_ = flowType_;
        result.roleMap_ = internalGetRoleMap();
        result.roleMap_.makeImmutable();
        result.applicate_ = applicate_;
        result.departmentId_ = departmentId_;
        result.recordId_ = recordId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.changwu.flowCenterProtobuf.FlowProtos.Flow) {
          return mergeFrom((com.changwu.flowCenterProtobuf.FlowProtos.Flow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.changwu.flowCenterProtobuf.FlowProtos.Flow other) {
        if (other == com.changwu.flowCenterProtobuf.FlowProtos.Flow.getDefaultInstance()) return this;
        if (!other.getFlowType().isEmpty()) {
          flowType_ = other.flowType_;
          onChanged();
        }
        internalGetMutableRoleMap().mergeFrom(
            other.internalGetRoleMap());
        if (!other.getApplicate().isEmpty()) {
          applicate_ = other.applicate_;
          onChanged();
        }
        if (other.getDepartmentId() != 0) {
          setDepartmentId(other.getDepartmentId());
        }
        if (other.getRecordId() != 0) {
          setRecordId(other.getRecordId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.changwu.flowCenterProtobuf.FlowProtos.Flow parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.changwu.flowCenterProtobuf.FlowProtos.Flow) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object flowType_ = "";
      /**
       * <code>string flowType = 1;</code>
       * @return The flowType.
       */
      public java.lang.String getFlowType() {
        java.lang.Object ref = flowType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          flowType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string flowType = 1;</code>
       * @return The bytes for flowType.
       */
      public com.google.protobuf.ByteString
          getFlowTypeBytes() {
        java.lang.Object ref = flowType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          flowType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string flowType = 1;</code>
       * @param value The flowType to set.
       * @return This builder for chaining.
       */
      public Builder setFlowType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        flowType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string flowType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlowType() {
        
        flowType_ = getDefaultInstance().getFlowType();
        onChanged();
        return this;
      }
      /**
       * <code>string flowType = 1;</code>
       * @param value The bytes for flowType to set.
       * @return This builder for chaining.
       */
      public Builder setFlowTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        flowType_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> roleMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetRoleMap() {
        if (roleMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              RoleMapDefaultEntryHolder.defaultEntry);
        }
        return roleMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableRoleMap() {
        onChanged();;
        if (roleMap_ == null) {
          roleMap_ = com.google.protobuf.MapField.newMapField(
              RoleMapDefaultEntryHolder.defaultEntry);
        }
        if (!roleMap_.isMutable()) {
          roleMap_ = roleMap_.copy();
        }
        return roleMap_;
      }

      public int getRoleMapCount() {
        return internalGetRoleMap().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; roleMap = 2;</code>
       */

      @java.lang.Override
      public boolean containsRoleMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetRoleMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getRoleMapMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getRoleMap() {
        return getRoleMapMap();
      }
      /**
       * <code>map&lt;string, string&gt; roleMap = 2;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getRoleMapMap() {
        return internalGetRoleMap().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; roleMap = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getRoleMapOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetRoleMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; roleMap = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getRoleMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetRoleMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearRoleMap() {
        internalGetMutableRoleMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; roleMap = 2;</code>
       */

      public Builder removeRoleMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableRoleMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableRoleMap() {
        return internalGetMutableRoleMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; roleMap = 2;</code>
       */
      public Builder putRoleMap(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableRoleMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; roleMap = 2;</code>
       */

      public Builder putAllRoleMap(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableRoleMap().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object applicate_ = "";
      /**
       * <code>string applicate = 3;</code>
       * @return The applicate.
       */
      public java.lang.String getApplicate() {
        java.lang.Object ref = applicate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          applicate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string applicate = 3;</code>
       * @return The bytes for applicate.
       */
      public com.google.protobuf.ByteString
          getApplicateBytes() {
        java.lang.Object ref = applicate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          applicate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string applicate = 3;</code>
       * @param value The applicate to set.
       * @return This builder for chaining.
       */
      public Builder setApplicate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        applicate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string applicate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplicate() {
        
        applicate_ = getDefaultInstance().getApplicate();
        onChanged();
        return this;
      }
      /**
       * <code>string applicate = 3;</code>
       * @param value The bytes for applicate to set.
       * @return This builder for chaining.
       */
      public Builder setApplicateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        applicate_ = value;
        onChanged();
        return this;
      }

      private int departmentId_ ;
      /**
       * <code>int32 departmentId = 4;</code>
       * @return The departmentId.
       */
      @java.lang.Override
      public int getDepartmentId() {
        return departmentId_;
      }
      /**
       * <code>int32 departmentId = 4;</code>
       * @param value The departmentId to set.
       * @return This builder for chaining.
       */
      public Builder setDepartmentId(int value) {
        
        departmentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 departmentId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDepartmentId() {
        
        departmentId_ = 0;
        onChanged();
        return this;
      }

      private int recordId_ ;
      /**
       * <code>int32 recordId = 5;</code>
       * @return The recordId.
       */
      @java.lang.Override
      public int getRecordId() {
        return recordId_;
      }
      /**
       * <code>int32 recordId = 5;</code>
       * @param value The recordId to set.
       * @return This builder for chaining.
       */
      public Builder setRecordId(int value) {
        
        recordId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 recordId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRecordId() {
        
        recordId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Flow.Flow)
    }

    // @@protoc_insertion_point(class_scope:Flow.Flow)
    private static final com.changwu.flowCenterProtobuf.FlowProtos.Flow DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.changwu.flowCenterProtobuf.FlowProtos.Flow();
    }

    public static com.changwu.flowCenterProtobuf.FlowProtos.Flow getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Flow>
        PARSER = new com.google.protobuf.AbstractParser<Flow>() {
      @java.lang.Override
      public Flow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Flow(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Flow> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Flow> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.changwu.flowCenterProtobuf.FlowProtos.Flow getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Flow_Flow_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Flow_Flow_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Flow_Flow_RoleMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Flow_Flow_RoleMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027src/protobuf/flow.proto\022\004Flow\"\255\001\n\004Flow" +
      "\022\020\n\010flowType\030\001 \001(\t\022(\n\007roleMap\030\002 \003(\0132\027.Fl" +
      "ow.Flow.RoleMapEntry\022\021\n\tapplicate\030\003 \001(\t\022" +
      "\024\n\014departmentId\030\004 \001(\005\022\020\n\010recordId\030\005 \001(\005\032" +
      ".\n\014RoleMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001B\036\n\020com.changwu.FlowB\nFlowProtosb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Flow_Flow_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Flow_Flow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Flow_Flow_descriptor,
        new java.lang.String[] { "FlowType", "RoleMap", "Applicate", "DepartmentId", "RecordId", });
    internal_static_Flow_Flow_RoleMapEntry_descriptor =
      internal_static_Flow_Flow_descriptor.getNestedTypes().get(0);
    internal_static_Flow_Flow_RoleMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Flow_Flow_RoleMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
