server:
  port: 8080
spring:
  application:
    name: oa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/oa?serverTimezone=UTC
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000